### ISSUE TITLE
Any idea how one would integrate Reactotron with this?

### ISSUE THREAD

**Issue by i-am-the-slime** [felixSchl/purescript-react-redux-saga-example#1]
I think Reactotron is a pretty cool app that also has saga support. How would you set it up?
https://github.com/infinitered/reactotron

**Comment by felixSchl** [comment]
purescript-redux-saga leans on the ideas of redux-saga but does not aim to be compatible with, or let alone to compile down to generator functions so I highly doubt that anything like that would be possible out of the box. I might update the README to clarify that.

**Comment by i-am-the-slime** [comment]
Ah I see. I was wondering how to even produce generator functions with Purescript.
